name: Creare Release

on:
  push:
    tags:
      - 'v*' # Rulează workflow-ul pentru orice tag care începe cu 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creați un Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Lansare ${{ github.ref_name }}"
          body: |
            Aceasta este lansarea automată a versiunii ${{ github.ref_name }}.
